### ISSUE TITLE
.git/tags;~ doesn't work

### ISSUE THREAD

**Issue by mantle2048** [anishathalye/dotfiles#10]
Hi 
I install vim-fugitive and set the tags file in the .git folder, just like your [.vimrc](https://github.com/anishathalye/dotfiles/blob/master/vimrc#L214-L215) file
```
" fugitive
set tags^=.git/tags;~
```
But after opening the file with vim, I use `ctrl`+`]` and can’t jump to function definition, the following is the error message
```
E433: No tags file
E426: tag not found: policy
```
Then I found that the vim-fugitive plugin seems to have [removed the support for .git/tags ](https://github.com/tpope/vim-fugitive/issues/1505)

So I want to ask if `set tags^=.git/tags;~` in .vimrc is invalid, or if I misunderstood something

Finally, thank you for the Missing-Semester course, it has benefited me a lot.

**Comment by bobwhitelock** [comment]
That line just tells Vim to load the tags from that file, but I think you'll still need to run something to generate them there. Looks like [`git ctags`](https://github.com/anishathalye/dotfiles/blob/63131479f69634843989ac1e07e9ee94b9f21935/gitconfig#L55) in this repo will do that.

Or you could try out something like [this approach](https://tbaggery.com/2011/08/08/effortless-ctags-with-git.html) to have your tags auto-update on each git commit/checkout etc, via git hooks, not sure if @anishathalye does something similar to this.

**Comment by anishathalye** [comment]
Yeah, so vim-fugitive doesn't auto-generate tags anymore. As Bob said, I manually run [this `git ctags`](https://github.com/anishathalye/dotfiles/blob/004b8a94a3bea4750d3d7ce88e438cee59163430/gitconfig#L55) alias when I want to (re-)generate tags, and the `set tags^=.git/tags;~` picks up these tags. I don't personally use the git hooks approach.

**Comment by mantle2048** [comment]
Thank you, I get it!
