### ISSUE TITLE
vim ctrlp repository is unmaintained

### ISSUE THREAD

**Issue by ghost** [anishathalye/dotfiles#3]
Just a heads up :)
Your .gitmodules file is pointing to https://github.com/kien/ctrlp.vim.git but the repository appears to be unmaintained. The new maintained repository is here https://github.com/ctrlpvim/ctrlp.vim

**Comment by anishathalye** [comment]
Thanks for the heads up! :)

Fixed in c332d4c7f00ce672d8fa2676700132a3ba5b8368.
