### ISSUE TITLE
Installation of plugins via ./install

### ISSUE THREAD

**Issue by tyr898** [anishathalye/dotfiles#7]
I was going through your dotfiles for some inspiration on how to use dotbot. One thing I have been wondering is how to automatically install certain plugins or at the very least plugin managers. How do you manage this?

For example, through your .gitmodules file, I can see that you use pathogen (?) or something similar to keep your plugins updated (I use vim-plug). Could you explain a bit about these dotfiles help you install plugins on a new machine?

For example, in your .gitmodules, you have this:
```
[submodule "vim/bundle/vim-markdown"]
	path = vim/pack/vendor/start/vim-markdown
	url = https://github.com/tpope/vim-markdown
	ignore = untracked
```
and have some shell commands in your `.install.conf.yaml` that supposedly facilitate plugin installation

I modified my ~/.dotfiles/.gitmodules to:
```
[submodule "dotbot"]
	path = dotbot
	url = https://github.com/anishathalye/dotbot
    ignore = dirty

[submodule "vim/test/vim-markdown"]
	path = vim/test/vim-markdown
	url = https://github.com/tpope/vim-markdown
	ignore = untracked
```
and manually ran:
```bash
git submodule sync --recursive && git submodule update --init --recursive # unaliased git update-submodules
```
but this was the only output:
```
Synchronizing submodule url for 'dotbot'
Synchronizing submodule url for 'dotbot/lib/pyyaml'
```

Nothing showed up in` vim/test/` either. Could you explain in further detail what way in which you are installing plugins? Right now I am making do my installing plugin managers manually, but I'm not sure if there is a better approach with dotbot.

**Comment by anishathalye** [comment]
I wouldn't modify the `.gitmodules` file directly. You can use the `git submodule` family of commands, e.g. `git submodule add`, to add them.

**Comment by tyr898** [comment]
Has this been documented somewhere? I believe the way that things work in Vim plugin managers is that you execute some ex command like `:PlugInstall` and the plugin manager clones the repos for you in the appropriate folder. Does this mean you would have to add submodules for those repositorys manually to be compatible with dotbot (and not have git repos inside a submodule?)

**Comment by anishathalye** [comment]
This is independent of Dotbot. E.g. Vim 8 will automatically load packages in a particular directory (https://shapeshed.com/vim-packages/). You can put them there using Git submodules.

**Comment by tyr898** [comment]
I see.. Please excuse my inexperience. In summary, the way these dotfiles work for plugins is that using Git submodules, the Github repo for the plugin is "cloned" using `git submodule add ...` to the appropriate directory.

If we want to remove the plugin, we simply modify `.gitmodules` as done here: [b1f82c9](https://github.com/anishathalye/dotfiles/commit/b1f82c91a9244c7dfda9e04f17f493eff43b606b)? Do we remove the files as shown [here](https://gist.github.com/myusuf3/7f645819ded92bda6677) or did you do something different for that commit?

Do we still need to do this step using this method: Run rm -rf .git/modules/path_to_submodule (no trailing slash) when removing a submodule or will git handle it?

**Comment by anishathalye** [comment]
Yes, that's correct, I use `git submodule add` to clone the plugin as a submodule. When the dotfiles directory is cloned, the `git submodule update ...` command is used to check out the appropriate versions of all the submodules. Reading the [documentation](https://git-scm.com/book/en/v2/Git-Tools-Submodules) on submodules might help with understanding this.

To remove a plugin, you can just `git rm` the file, and Git will know that it's a submodule and make the appropriate modifications to `.gitmodules`. If you look at b1f82c91a9244c7dfda9e04f17f493eff43b606b, you'll see that the `.gitmodules` file was edited (automatically by git, when I ran `git rm`), and the `emacs.d/vendor/undo-tree` submodule reference was also deleted.

**Comment by tyr898** [comment]
Regarding submodules, is there any relevance to `ignore=untracked` as in your .gitmodules:
```
[submodule "vim/bundle/vim-markdown"]
	path = vim/pack/vendor/start/vim-markdown
	url = https://github.com/tpope/vim-markdown
	ignore = untracked
```
According to [documentation](https://git-scm.com/docs/gitmodules#Documentation/gitmodules.txt-submoduleltnamegtignore): "Only untracked files in submodules will be ignored. Committed differences and modifications to tracked files will show up."

I suppose this would only be relevant if you are actually modifying the code in your submodules. Otherwise, it makes no difference, correct?

**Comment by anishathalye** [comment]
It's relevant when e.g. untracked temporary files are created in submodule directories.

**Comment by tyr898** [comment]
Does this shell command from `.install.conf.yaml` achieve something similar? Deleting the untracked files (even in those submodules that have `ignore = untracked`) to create a fresh dotfiles directory every time `./install` is run? (BTW perhaps you should call this on `vim/pack/vendor` instead of `vim/bundle` since you don't use pathogen anymore)
```yaml
  - >
    git cleanall -f
    emacs.d/vendor/
    irssi/scripts/vendor/
    jupyter/nbextensions/
    shell/plugins/
    vim/bundle/
    zsh/plugins/
```

**Comment by anishathalye** [comment]
Yeah, I think this removes submodules that were deleted on another machine, and then we `git pull`ed on the current machine. And thanks for pointing out the vim/pack/vendor thing.

**Comment by tyr898** [comment]
Thank you for this crash course in maintaining plugins without git repos! Unfortunately I think I had the impression that plugins must have a corresponding plugin manager. Most popular ones automatically use `git clone` instead of `git submodule add`, and I think I was looking in the wrong place in trying to modify the plugin managers to use submodules instead of repos. Now I know better!
