### ISSUE TITLE
What did you remap `C-h` prefix to?

### ISSUE THREAD

**Issue by tyr898** [anishathalye/dotfiles#9]
I see that you have:
```
  (define-key evil-normal-state-map (kbd "C-k") 'evil-window-up)
  (define-key evil-normal-state-map (kbd "C-j") 'evil-window-down)
  (define-key evil-normal-state-map (kbd "C-h") 'evil-window-left)
  (define-key evil-normal-state-map (kbd "C-l") 'evil-window-right)
```

The rest are pretty redundant with Evil, but `C-h` should still be useful. How do you access things like Info ? `C-z C-h i` would work, but usually you don't want to leave Evil mode right? Is there a clever workaround you have devised? Just wondering since I couldn't find any such remap in your `packages.el`

**Comment by anishathalye** [comment]
Uh I don't have a particularly well-thought-out solution to this problem 😛

I'm not an expert Emacs user. I basically use Vim for everything, and Emacs for Coq development with [Proof General](https://proofgeneral.github.io/) and Racket with [racket-mode](https://www.racket-mode.com/), and I haven't run into any major problems in practice with my fairly basic usage of the program.

**Comment by tyr898** [comment]
Haha I see. I use it for Racket and Org mode mostly so not extensive either.

So do you exit out of evil using `C-z` and then use `C-h i` when wanting to access Emacs manuals, etc?

**Comment by anishathalye** [comment]
That, or I use the GUI 😅
